# Segunda implementação, seguna unidade
> Sinais e sistemas

## Alunos
Gabriel Calabrese
Vinícius José

Sugestões do Prof. Diego:
1. Explicar linha by linha do codigo
2. Implementar mudando o Kernel de conolução

# Código

In [ ]:
# Ambiente
!pip install matplotlib
!pip install numpy
!pip install pip install scikit-image
!pip install scipy

In [ ]:
# Importações

import os
from scipy import signal
import matplotlib.pyplot as plt
import numpy as np
from skimage.color import rgb2gray
from skimage import io
# import skimage

In [ ]:
# Variáveis

Matriz = np.array([[1,1,1,1], [1,1,1,1], [0,0,0,0], [0,0,0,0]]) # Matriz da informação (será alterada)
#kernel = np.array([[-1,-1], [1,1]])
Matriz # Exibição
#kernel

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
kernel = np.array([[1,1], [-1,-1]]) # Matriz do kernel
kernel # Exibição

array([[ 1,  1],
       [-1, -1]])

![image.png](attachment:image.png)

![image-2.png](attachment:image-2.png)

In [ ]:
# Operação de convolução

temp = signal.convolve2d(Matriz , kernel, mode='same')
temp # Exibição

array([[ 1,  2,  2,  2],
       [ 0,  0,  0,  0],
       [-1, -2, -2, -2],
       [ 0,  0,  0,  0]])

Resultado:

![image.png](attachment:image.png)

Resultado aparente:
![image.png](attachment:image.png)


# Convolução de Imagem

In [ ]:
def show_convolve2d(imagen, kernel):

    %matplotlib notebook
    plt.ion()

    imagen_list = []
    for d in range(3):
        temp = signal.convolve2d(imagen[:,:,d] , kernel,  boundary='symm',mode='same')
        imagen_list.append(temp)

    imagen_filt = np.stack(imagen_list, axis=2)
    imagen_filt[imagen_filt > 255] = 255
    imagen_filt[imagen_filt < 0] = 0
    imagen_filt = imagen_filt.astype("uint8")

    plt.subplot(1,2,1)
    io.imshow(imagen_filt)
    plt.axis('off')

    plt.subplot(1,2,2)
    io.imshow(imagen)
    plt.axis('off')

    io.show()

In [ ]:
filename = os.path.join('assets/', 'tigre.jpg')
imagen = io.imread(filename)

FileNotFoundError: ignored

In [ ]:
k=np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
show_convolve2d(imagen,k)